{
 "title": "Projet MLops",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[1m])\n/\nrate(prediction_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prediction_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency sum",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "prediction_latency_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "prediction_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}